### ISSUE TITLE
DERP_VERIFY_CLIENTS env option not working

### ISSUE THREAD

**Issue by houance** [fredliang44/derper-docker#11]
According to the official documentation, if you want to use the DERP_VERIFY_CLIENTS Option on a custom derp server, you need to install a tailscale instance. Does this mean that the existing dockerfile cannot enable the DERP_VERIFY_CLIENTS Option? Because I don’t see the steps to install tailscale in the dockerfile.

official documentation : https://tailscale.com/kb/1118/custom-derp-servers#step-2-adding-derp-servers-to-your-tailnet

**Comment by LinEvil** [comment]
You should install tailscale on your host machine and mount `/var/run/tailscale/tailscaled.sock` to the container
