### ISSUE TITLE
启动之后绑定我自己的域名然后通过https://我的域名访问 报错 后台弹出如下错误

### ISSUE THREAD

**Issue by chenxudong2020** [fredliang44/derper-docker#2]
![1640267163(1)](https://user-images.githubusercontent.com/61214170/147249373-a0c64393-eac4-4266-bb29-406a0133aaf4.png)

**Comment by fredliang44** [comment]
this is not related to the current repo, please read the official documents for details. It seems the error caused by you havent provide the certificate for the derper service.
