### ISSUE TITLE
Can't set DERP_STUN and DERP_VERIFY_CLIENTS to false

### ISSUE THREAD

**Issue by tzhao11** [fredliang44/derper-docker#4]
derper seems to parse boolean argument solely based on whether the corresponding command line flag exists or not, regardless of its value, so passing in `--stun false` or `--verify-clients false` has no effect. We might need to stop passing these flags to derper when `DERP_STUN` and `DERP_VERIFY_CLIENTS` are not set to `true`.

I can't think of a clean way to do this without introducing an entrypoint script. Any ideas?

**Comment by fredliang44** [comment]
thanks for your report, let me revert the changes first.

**Comment by fredliang44** [comment]
it seems derper using the "flag" package, it seems switching to "=" is working.

https://github.com/tailscale/tailscale/blob/bc537adb1a6a9794f7e74337880cc63c915d19f9/cmd/derper/derper.go#L123

![image](https://user-images.githubusercontent.com/22412638/147365984-3a321ca7-1b28-4877-97cc-6925eba32ef7.png)

**Comment by fredliang44** [comment]
@tzhao11 I updated the command in the main branch, could you help me double check whether it works as expected now?

**Comment by tzhao11** [comment]
@fredliang44 working as expected now. Thanks for the fix!
