### ISSUE TITLE
Please update README with UDP port mapping

### ISSUE THREAD

**Issue by yaleh** [fredliang44/derper-docker#5]
Hi there,

I noticed that the example in README reads:

`docker run -e DERP_DOMAIN=derper.your-domain.com -p 80:80 -p 443:443 -p 3478:3478 fredliang/derper`

But 3478 port in the docker instance is a UDP port. Please update it. Thanks.

**Comment by yaleh** [comment]
And package ca-certificates is also necessary for letsencrypt.

**Comment by fredliang44** [comment]
@yaleh thanks for reporting these issues, I will fix them shortly.

**Comment by fredliang44** [comment]
@yaleh  I made a fix for the problems, could you help me double check whether it works as expected now?
please feel free to reopen this issue if you met any other problem.

**Comment by yaleh** [comment]
Perfect.

I tried it, it works smoothly now.

Thanks for your effort.
