### ISSUE TITLE
fix DERP_CERT_DIR

### ISSUE THREAD

**Issue by veritas501** [fredliang44/derper-docker#6]
https://github.com/fredliang44/derper-docker/blob/e546a8d749af62204d3c427b70a33e70c664437f/Dockerfile#L15

https://github.com/fredliang44/derper-docker/blob/e546a8d749af62204d3c427b70a33e70c664437f/Dockerfile#L19

Change `ENV DERP_CERT_DIR /app/certs` to `ENV DERP_CERT_DIR /app/cert`

**Comment by fredliang44** [comment]
nice catch
